### ISSUE TITLE
Recommended parameters for medium length paragraph

### ISSUE THREAD

**Issue by pgrandinetti** [Vamsi995/Paraphrase-Generator#10]
I was testing this with some paragraph from wikipedia. I see little no changes in the text after paraphrase. What would be good values for the parameters for this type of text?

Here's what I have (I used the Dockerfile that I PR-ed few days ago).

```
curl -XPOST localhost:5000/run_forward \
-H 'content-type: application/json' \
-d '{"sentence": "Football is a family of team sports that involve, to varying degrees, kicking a ball to score a goal. Unqualified, the word football normally means the form of football that is the most popular where the word is used. Sports commonly called football include association football (known as soccer in some countries); gridiron football (specifically American football or Canadian football); Australian rules football; rugby football (either rugby union or rugby league); and Gaelic football.[1][2] These various forms of football share to varying extent common origins and are known as football codes. ",
     "decoding_params": {"tokenizer": "",  # default
                                       "max_len": 1024,
                                       "strategy": "", # default
                                       "top_k": 168,
                                       "top_p": 0.95,
                                       "return_sen_num": 3}}'

{"data":["1. Football is a family of team sports which involve, to varying degrees, kicking a ball to score a goal. Unqualified, the word football normally means the form of football most popular where the word is used. Sports commonly called football include association football (known as soccer in some countries), gridiron football (specifically American football or Canadian football), Australian rules football, rugby football (either rugby union or rugby league) and gaelic football.","2. Football is a family of team sports which involve kicking a ball to score a goal in varying degrees. The word football normally means the form of football most popular where the word is used. Sports commonly called football include association football (known as soccer in some countries), gridiron football (specifically American football or Canadian football); Australian rules football; rugby football (either rugby union or rugby league) and gaelic football.","3. Football is a family of team sports that involve to varying degrees kicking a ball to score a goal, unqualified, the word football normally means the most popular form of football when the word is used. Football sports commonly called football include association football (known in some countries as soccer ; American football ; Canadian football ; Australian rules football ; rugby football ; either rugby union or rugby league ; and gaelic football."]}
```

**Comment by pgrandinetti** [comment]
Yes I can so something "moving" now:

Input:
> Football is a family of team sports that involve, to varying degrees, kicking a ball to score a goal. Unqualified, the word football normally means the fo    rm of football that is the most popular where the word is used. Sports commonly called football include association football (known as soccer in some coun    tries); gridiron football (specifically American football or Canadian football); Australian rules football; rugby football (either rugby union or rugby le    ague); and Gaelic football.[1][2] These various forms of football share to varying extent common origins and are known as football codes.

Output (1st only):
> Football is a family of team sports that involve kicking a ball to score a goal. The word football means normally the most popular form of football where     the word is used : association football (known as soccer in some countries), gridiron football (specifically American football or Canadian football), Aust    ralian rules football, rugby football (either rugby union or rugby league) and Gaelic football

What are the rules-of-thumb for the parameters? Any docs I can look up on this?

**Comment by Vamsi995** [comment]
You can check this blog out.  [How to generate text: using different decoding methods for language generation with Transformers](https://huggingface.co/blog/how-to-generate)
