### ISSUE TITLE
reproducible Docker container

### ISSUE THREAD

**Issue by pgrandinetti** [Vamsi995/Paraphrase-Generator#8]
I have a minimal reproducible Dockerfile that I am using to run some tests.
Is that of any interest if I submit a PR? https://github.com/Vamsi995/Paraphrase-Generator/compare/master...pgrandinetti:master

On a related note, it would be great if the required input fields for the endpoints were better documented.

Thanks.

**Comment by Vamsi995** [comment]
Yeah that is fine.

**Comment by pgrandinetti** [comment]
closing as per #9
